# GitLab CI/CD Pipeline Configuration Reference: https://docs.gitlab.com/ee/ci/yaml/

default:
  image: node:latest
  # https://docs.gitlab.com/ee/ci/caching/#caching-nodejs-dependencies
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

# https://docs.gitlab.com/ee/ci/yaml/#stages
stages:
  - build
  - test
  - deploy

.build:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      # TODO add build artifacts (e.g. dist, build, public)
      # - build

.deploy:
  stage: deploy
  script:
    - yarn deploy

.staging:
  variables:
    PUBLIC_URL: $STAGING_PUBLIC_URL
    AUTH0_DOMAIN: $STAGING_AUTH0_DOMAIN
    AUTH0_CLIENTID: $STAGING_AUTH0_CLIENTID
    AUTH0_CALLBACK_URL: $STAGING_AUTH0_CALLBACK_URL
    AUTH0_LOGOUT_URL: $STAGING_AUTH0_LOGOUT_URL

.production:
  variables:
    PUBLIC_URL: $PRODUCTION_PUBLIC_URL
    AUTH0_DOMAIN: $PRODUCTION_AUTH0_DOMAIN
    AUTH0_CLIENTID: $PRODUCTION_AUTH0_CLIENTID
    AUTH0_CALLBACK_URL: $PRODUCTION_AUTH0_CALLBACK_URL
    AUTH0_LOGOUT_URL: $PRODUCTION_AUTH0_LOGOUT_URL

build_staging:
  extends:
    - .build
    - .staging
  except:
    - /^release.*$/

build_production:
  extends:
    - .build
    - .production
  only:
    - /^release.*$/

test:
  stage: test
  script:
    - yarn test
  artifacts:
    paths:
      # TODO add test artifacts (e.g. coverage)
      # - coverage

lint:
  stage: test
  script:
    - yarn lint

deploy_staging:
  extends:
    - .deploy
    - .staging
  # https://docs.gitlab.com/ee/ci/environments.html#defining-environments
  environment:
    name: staging
    url: $STAGING_PUBLIC_URL
  only:
    - master

deploy_production:
  extends:
    - .deploy
    - .production
  # https://docs.gitlab.com/ee/ci/environments.html#defining-environments
  environment:
    name: production
    url: $PRODUCTION_PUBLIC_URL
  only:
    - /^release.*$/
