# GitLab CI/CD Pipeline Configuration Reference: https://docs.gitlab.com/ee/ci/yaml/

default:
  image: node:latest
  # https://docs.gitlab.com/ee/ci/caching/#caching-nodejs-dependencies
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

# https://docs.gitlab.com/ee/ci/yaml/#stages
stages:
  - build
  - test
  - deploy

.build:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      # TODO add build artifacts (e.g. dist, build, public)
      # - build

.deploy:
  stage: deploy
  script:
    - yarn deploy

.staging:
  variables:
    PUBLIC_URL: $STAGING_PUBLIC_URL
    AWS_REGION: $STAGING_AWS_REGION
    AWS_ACCESS_KEY_ID: $STAGING_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $STAGING_AWS_SECRET_ACCESS_KEY
    AWS_S3_BUCKET_NAME: $STAGING_AWS_S3_BUCKET_NAME

.production:
  variables:
    PUBLIC_URL: $PRODUCTION_PUBLIC_URL
    AWS_REGION: $PRODUCTION_AWS_REGION
    AWS_ACCESS_KEY_ID: $PRODUCTION_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $PRODUCTION_AWS_SECRET_ACCESS_KEY
    AWS_S3_BUCKET_NAME: $PRODUCTION_AWS_S3_BUCKET_NAME

build_staging:
  extends:
    - .build
    - .staging
  except:
    - /^release.*$/

build_production:
  extends:
    - .build
    - .production
  only:
    - /^release.*$/

test:
  stage: test
  script:
    - yarn test
  artifacts:
    paths:
      # TODO add test artifacts (e.g. coverage)
      # - coverage

lint:
  stage: test
  script:
    - yarn lint

deploy_staging:
  extends:
    - .deploy
    - .staging
  # https://docs.gitlab.com/ee/ci/environments.html#defining-environments
  environment:
    name: staging
    url: $STAGING_PUBLIC_URL
  only:
    - master

deploy_production:
  extends:
    - .deploy
    - .production
  # https://docs.gitlab.com/ee/ci/environments.html#defining-environments
  environment:
    name: production
    url: $PRODUCTION_PUBLIC_URL
  only:
    - /^release.*$/
