version: "3"

services:
  prism:
    image: stoplight/prism:3
    ports:
      - 4010:4010
    volumes:
      - ./openapi/mocked-api.yml:/openapi/mocked-api.yml
    command: >
      mock -p 4010 --host 0.0.0.0 /openapi/mocked-api.yml
  swagger-ui:
    image: "swaggerapi/swagger-ui"
    ports:
      - 80:8080
    environment:
      - API_URL=openapi/mocked-api.yml
    volumes:
      - "./openapi/mocked-api.yml:/usr/share/nginx/html/openapi/mocked-api.yml"
