input {
	tcp {
		port => 5000
	}
	http {
		port => "5050"
		codec => "json"
	}
}

output {
	stdout {
	}
	elasticsearch {
		hosts => "${ELASTIC_HOST}"
		user => "${ELASTIC_USER}"
		password => "${ELASTIC_PASSWORD}"
	}
}
